###################### local info



server:
  port: 8080

## 윤영 db 연결 테스트
spring:
  datasource:
#    url: jdbc:p6spy:mariadb://52.78.56.230:3306/posdb   ## g9시스템 공용 아이피
#    username: admin
#    password: G9system!@
#    url: jdbc:p6spy:mariadb://3.34.136.152:3306/posdb?serverTimezone=Asia/Seoul      ## jjpos.store DB
#    username: root
#    password: 1234
###### 로컬에서 서버 db 테스트 하기 위해 설정 함.
    url: jdbc:p6spy:mariadb://localhost:3306/posdb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 60000        # 60초 후 유휴 커넥션 닫기
      max-lifetime: 1800000      # 30분 후 커넥션 재생성
      keepalive-time: 300000     # 5분마다 ping
      connection-test-query: SELECT 1


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    repositories:
      bootstrap-mode: default  # ⚠️ deferred는 rollback-only 이슈 유발 가능
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        format_sql: true
        jpaql:
          strict: false
        query:
          fail_on_pagination_over_collection_fetch: false
        default_batch_fetch_size: 100

   
  devtools:
    restart:
      enabled: true

#  data:
#    redis:
#      host: localhost
#      port: 6379

# keycloak config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak-home}/realms/jjpos
#          issuer-uri: https://jjpos.store/auth/realms/jjpos

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jjsoft.pos.dto
  configuration:
    map-underscore-to-camel-case: true	
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.resource.transaction: error
    org.hibernate.internal.AbstractSharedSessionContract: error
    org.springframework.data.jpa.repository.query: warn


## App Base Info 
app: 
  base-url: http://localhost
  keycloak-home: ${app.base-url}:8180 
  mode: local
  keycloak-db-url: jdbc:mariadb://localhost:3306/keycloakdb
  keycloak-db-user: root
  keycloak-db-pwd: 1234
### cj db 테스트 위해 잠시 설정 
#  keycloak-db-url: jdbc:mariadb://g9-prd-store-mariadb.cxwwuys2okv0.ap-northeast-2.rds.amazonaws.com/keycloakdb
#  keycloak-db-user: admin
#  keycloak-db-pwd: Zmffkdnem1!



## 인증서버 설정 ㅈ정보
keycloak:
  auth-server-url: ${app.keycloak-home}
  realm: jjpos
  admin-username: admin
  admin-password: admin
  client-id: jjpos-backend
  idp-alias: oidc-kakao
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

## aws object storagy를 써서 경로 이제 안씀.
file:
  upload:
    image-path: E:/dev/uploads/images/products/
    access-url-prefix: /upload/images/products/	


## aws object storagy 정보 
aws:
  s3:
#    bucket: jjpos-image-bucket
#    region: ap-northeast-2
#    access-key: AKIAX3TTOMRAXG3A4BW6                      # 발급받은 Access Key   
#    secret-key: RxbfdfBDcuryI0ybLKHQZNWXVEl4iH6n+FZIKZgG  # 발급받은 Secret Key

    bucket: ${AWS_S3_BUCKET}
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
         
#
#logging:
#  level:
#    root: info
#    org.mybatis: debug
#    org.apache.ibatis: debug
#    org.mybatis.spring.SqlSessionUtils: debug
#    org.springframework.jdbc.core: debug
#    org.springframework.jdbc.datasource: debug
#    java.sql: debug
