##### g9system.com 설정 정보 

server:
  port: 8080

  ### 지구 스토어 yml
  
## 윤영 db 연결 테스트
spring:
  datasource:
    url: jdbc:mariadb://g9-prd-store-mariadb.cxwwuys2okv0.ap-northeast-2.rds.amazonaws.com:3306/posdb      ## cj aws db 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 300000        # 60초 후 유휴 커넥션 닫기
      max-lifetime: 1800000      # 30분 후 커넥션 재생성
      keepalive-time: 240000     # 5분마다 ping
#      connection-test-query: SELECT 1
  


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    repositories:
      bootstrap-mode: default  # ⚠️ deferred는 rollback-only 이슈 유발 가능
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        format_sql: true
        jpaql:
          strict: false
        query:
          fail_on_pagination_over_collection_fetch: false
        default_batch_fetch_size: 100
        jdbc:
          use_get_generated_keys: true
        id:
          new_generator_mappings: false

   
  devtools:
    restart:
      enabled: true

#  data:
#redis:
#  host: localhost
#  port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak-home}/realms/jjpos

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jjsoft.pos.dto
  configuration:
    map-underscore-to-camel-case: true	
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.resource.transaction: error
    org.hibernate.internal.AbstractSharedSessionContract: error
    org.springframework.data.jpa.repository.query: warn

## App Base Info 
app: 
  base-url: https://auth.ji9store.com
  keycloak-home: ${app.base-url}
  mode: prod
  keycloak-db-url: jdbc:mariadb://g9-prd-store-mariadb.cxwwuys2okv0.ap-northeast-2.rds.amazonaws.com:3306/keycloakdb
  keycloak-db-user: ${DB_USERNAME}
  keycloak-db-pwd: ${DB_PASSWORD}

## 인증서버 설정 ㅈ정보
keycloak:
  auth-server-url: ${app.keycloak-home}
  realm: jjpos
  client-id: jjpos-backend
  idp-alias: oidc-kakao
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

file:
  upload:
    image-path: E:/dev/uploads/images/products/
    access-url-prefix: /upload/images/products/	


## aws object storagy 정보   ## 아직 만들어 지지 않아서 개발서버 사용중 정보 DEV 서버 
aws:
  s3:
    bucket: g9store-image-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
#
#logging:
#  level:
#    root: info
#    org.mybatis: debug
#    org.apache.ibatis: debug
#    org.mybatis.spring.SqlSessionUtils: debug
#    org.springframework.jdbc.core: debug
#    org.springframework.jdbc.datasource: debug
#    java.sql: debug
